# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Standard go vet
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Staticcheck checks (includes gosimple)
    - unused        # Check for unused code
    - misspell      # Check for misspelled words
    - revive        # Fast linter
    - bodyclose     # Check HTTP response bodies are closed
    - gocritic      # Comprehensive linter
    - gosec         # Security issues
    - unconvert     # Remove unnecessary conversions
    - unparam       # Detect unused function parameters

formatters:
  enable:
    - gofmt         # Check formatting
    - goimports     # Check import formatting

formatters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/middlendian/llima-box

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    check-shadowing: true

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    # Gosec - intentional security exceptions for Lima VM trust model
    - linters:
        - gosec
      text: "G106:"
    - linters:
        - gosec
      text: "G304:"
    - linters:
        - gosec
      text: "G301:"
    - linters:
        - gosec
      text: "G306:"
